"""empty message

Revision ID: 041b335ed42b
Revises: ff5f4a64a70a
Create Date: 2024-02-22 12:05:44.468184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041b335ed42b'
down_revision = 'ff5f4a64a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscribe_to_package', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_subscribe_to_package')

    # ### end Alembic commands ###
