"""empty message

Revision ID: 141838d1e067
Revises: d6ac0ae646e9
Create Date: 2023-11-27 14:06:38.691588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141838d1e067'
down_revision = 'd6ac0ae646e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'community', ['community_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
