"""empty message

Revision ID: 42c45ed26180
Revises: 6206ef202ca3
Create Date: 2023-12-01 17:13:40.520661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c45ed26180'
down_revision = '6206ef202ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_timestamp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_timestamp')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
