"""empty message

Revision ID: 648bf20a5217
Revises: 141838d1e067
Create Date: 2023-11-29 09:37:44.530167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '648bf20a5217'
down_revision = '141838d1e067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=256),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
