"""empty message

Revision ID: 7f33d48b4575
Revises: 041b335ed42b
Create Date: 2024-02-22 16:01:33.036283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f33d48b4575'
down_revision = '041b335ed42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_package_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('standard_listing_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('featured_listing_desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('premium_listing_desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('premium_listing_desc')
        batch_op.drop_column('featured_listing_desc')
        batch_op.drop_column('standard_listing_desc')
        batch_op.drop_column('premium_package_desc')

    # ### end Alembic commands ###
