"""empty message

Revision ID: 85529beaf5fd
Revises: 4314913737df
Create Date: 2024-02-17 13:03:18.573703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85529beaf5fd'
down_revision = '4314913737df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('standard_listing', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('featured_listing', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('premium_listing', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('premium_listing')
        batch_op.drop_column('featured_listing')
        batch_op.drop_column('standard_listing')

    op.create_table('message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name='message_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name='message_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
