"""empty message

Revision ID: 893a800707ca
Revises: 
Create Date: 2023-11-22 09:49:29.988495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '893a800707ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.drop_column('brand_photo')
        batch_op.drop_column('brant_type')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brant_type', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('brand_photo', mysql.TEXT(), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
