"""empty message

Revision ID: 89d7b099bae8
Revises: 648bf20a5217
Create Date: 2023-11-30 16:06:32.746756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d7b099bae8'
down_revision = '648bf20a5217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trim', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('insured_uae', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('insured_uae')
        batch_op.drop_column('trim')

    # ### end Alembic commands ###
