"""empty message

Revision ID: d6ac0ae646e9
Revises: 893a800707ca
Create Date: 2023-11-22 10:58:29.173476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ac0ae646e9'
down_revision = '893a800707ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('listing_amenities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    with op.batch_alter_table('safety_features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_features', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('listing_amenities', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
