"""empty message

Revision ID: e1aac16b5f86
Revises: 42c45ed26180
Create Date: 2023-12-05 10:53:37.608374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1aac16b5f86'
down_revision = '42c45ed26180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('vin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('vin', ['vin'], unique=False)

    # ### end Alembic commands ###
