"""empty message

Revision ID: fe4a64e2ac21
Revises: e1aac16b5f86
Create Date: 2023-12-06 11:59:51.812445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe4a64e2ac21'
down_revision = 'e1aac16b5f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heavy_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('warranty', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('horse_power', sa.String(length=255), nullable=True))
        batch_op.drop_column('horse_condition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heavy_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horse_condition', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('horse_power')
        batch_op.drop_column('warranty')
        batch_op.drop_column('seller_type')

    # ### end Alembic commands ###
